### ISSUE TITLE
Google Sheets API Quota

### ISSUE THREAD

**Issue by ndom91** [joway/sheetsql#7]
I had an application where I was using the raw sheets API, and I am currently migrating it to use your library. So far so good, thanks for your work! Makes dealing with sheets much easier.

One problem I seem to still face, however, is the google sheets API quotas. Previously I just put timeouts into my loops where I was writing cells, etc. which only kind of worked to begin with. 

How do you suggest dealing with the quota? Can I artificially slow down any of the async loops? `for await of`, for example?

Thanks!

**Comment by joway** [comment]
Hi @ndom91 , 

Firstly, sheetsql will request to google APIs when you insert/update a record. So, if you change your record too frequently, you must need to catch the quota error and try it again. 

Secondly, there is no matter how frequently you query the data because sheetsql cache all data in memory and only refresh them when hit cache timeout. If you want to custom the cache timeout, you could use `cacheTimeoutMs`  option.  https://github.com/joway/sheetsql#example

By the way, I found a bug in sheetsql's cache and have fixed it. You should use the latest version(>=0.1.5). 

I'm glad it could help you to simplify your work. Please feel free to ask me if you have any other questions or advice.

Thanks!

**Comment by ndom91** [comment]
Hey thanks for the quick turnaround. I'll check out the new update. However, I'm having another issue:

I have two instances: `newData` and `masterData`. I'm trying to update `newData` like so:

```
await newData.update({
  RowNr: row.nr
}, {
  Status: row.status
})
```

Where I want to search for the `row.nr` in column 'RowNr' and update the field 'Status' to the value 'row.status'.

However what it does is copies the entire row from `newData` into the row number of `masterData` that matches `RowNr: row.nr`.

Am I missing something? Seems like maybe some logic got crossed up there.

**Comment by joway** [comment]
Aha! Yes, there is a bug when using multiple tables. Fixed it at https://github.com/joway/sheetsql/commit/b98d2af45554cbf6fc6a285e1de4046d71c2dc99. You really help me to improve this project better!

Thanks a lot!

**Comment by joway** [comment]
Can you try the version 0.1.6?

**Comment by ndom91** [comment]
No problem, thanks for being so responsive!

Looks much better now. Everything seems to be working :)
